# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 17:55
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='documents/', validators=[core.validators.validate_file_extension])),
            ],
        ),
    ]
