# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='proof',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
